# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Falana Dimaka
email: ravmalla@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another attempt at blogging by yours truly.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xenophene.github.io/" # the base hostname & protocol for your site
twitter_username: raveemalla
github_username:  xenophene

# Build settings
markdown: kramdown
